
spring:
  datasource:
    password: 13632554
    url: jdbc:mysql://localhost:3306/server
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
